apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
      - name: hotel-service
        image: hotel-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_SECURITY_USER_NAME
          valueFrom:
            secretKeyRef:
              name: basic-auth-secrets
              key: service-username
        - name: SPRING_SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: basic-auth-secrets
              key: service-password
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
spec:
  selector:
    app: hotel-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
