apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-service
  template:
    metadata:
      labels:
        app: loyalty-service
    spec:
      containers:
      - name: loyalty-service
        image: loyalty-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_SECURITY_USER_NAME
          valueFrom:
            secretKeyRef:
              name: basic-auth-secrets
              key: service-username
        - name: SPRING_SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: basic-auth-secrets
              key: service-password
---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-service
spec:
  selector:
    app: loyalty-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
