apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secrets
type: Opaque
data:
  admin-username: YWRtaW4=          # admin
  admin-password: cGFzc3dvcmQ=      # password
  service-username: c2VydmljZV91c2Vy  # service_user
  service-password: c2VydmljZV9wYXNz  # service_pass
