apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE_NAME
spec:
  template:
    spec:
      containers:
      - name: SERVICE_NAME
        env:
        - name: SPRING_SECURITY_USER_NAME
          valueFrom:
            secretKeyRef:
              name: basic-auth-secrets
              key: service-username
        - name: SPRING_SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: basic-auth-secrets
              key: service-password
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-password